### ISSUE TITLE
play command

### ISSUE THREAD

**Issue by iyordiii** [Spimy/Music-Bot-Development#4]
Hi,

When i do !play <song> he is joining the voice channel, and he says: "Started playing" and then he says instantly "playback ended"
What did i do wrong?

**Comment by Spimy** [comment]
@iyordiii Hello, the music bot is old and outdated. In order to fix this issue, you would have to move from YTDL-Core to YTDL-Core-Discord and make appropriate changes. I have no experience with said changes therefore I suggest to join my discord server @ http://discord.spimy.ga and contact @Ømega#5556 for help.
